# Ethereum Mainnet Fork CLI - Just Commands

# Start a local Ethereum node forked from mainnet (via Anvil & Alchemy)
start:
    anvil --fork-url https://eth-mainnet.g.alchemy.com/v2/Cjed1RpeFugEhFCpd2aNkuDaBYWprQM- --fork-block-number 23033603 --block-time 1

# Deploy contracts to local fork (using Foundry's forge script)
deploy:
    forge script script/DeployContracts.s.sol --rpc-url http://127.0.0.1:8545 --broadcast --private-key 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
