[package]
version = "0.1.0"
name = "atomic-swap-script"
edition = "2021"
default-run = "atomic-swap-script"

[[bin]]
name = "atomic-swap-script"
path = "src/bin/main.rs"


[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
sp1-sdk = "5.0.8"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
proofimpl-atomic-swap = { path = "../lib" }
dotenv = "0.15.0"

[build-dependencies]
sp1-build = "5.0.8"
