[wallet]
name = "maker"
type = "trader"
network = "regtest"

[keys]
# Maker wallet - initiates swaps
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
derivation_path = "m/84h/1h/1h"

[config]
electrum_url = "tcp://localhost:50001"
block_height = 0