[wallet]
name = "taker"
type = "trader"
network = "regtest"

[keys]
# Taker wallet - responds to swaps
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
derivation_path = "m/84h/1h/2h"

[config]
electrum_url = "tcp://localhost:50001"
block_height = 0